from __future__ import annotations

from dataclasses import dataclass
from difflib import SequenceMatcher
from pathlib import Path
import re
from typing import Iterable

import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Font


DEFAULT_INPUT_FILE = "松鹤堂196分店销售明细.xlsx"
DEFAULT_OUTPUT_FILE = "松鹤堂196分店销售明细_退货冲销检查.xlsx"
DEFAULT_COMPARE_SALES_FILE = "万众药房销售端.xlsx"
DEFAULT_COMPARE_MEDICAL_FILE = "万众药房医保端.csv"
DEFAULT_COMPARE_OUTPUT_FILE = "万众药房销售医保比对结果.xlsx"
DEFAULT_PRESCRIPTION_FILE = "松鹤堂处方明细.xlsx"
DEFAULT_PRESCRIPTION_MEDICAL_FILE = "松鹤堂医保端.csv"
DEFAULT_PRESCRIPTION_COMPARE_OUTPUT_FILE = "松鹤堂处方医保及处方药比对结果.csv"
DEFAULT_PRESCRIPTION_DRUG_CATALOG_FILE = "resources/处方药目录.xlsx"
DEFAULT_COLUMN_CONFIG_FILE = "列名配置.xlsx"

# Default column names. Actual input headers are read from the column config
# workbook generated by menu option 1.
COL_BILL_DATE = "销售时间整理"
COL_PRODUCT_NAME = "品名"
COL_PRICE = "零售价"
COL_QUANTITY = "数量"
COL_AMOUNT = "价税合计"
COL_APPROVAL_NO = "批准文号"
COL_OFFSET_ID = "冲销编号"
COL_SALES_ORDER_ID = "流水号"
COL_MEDICAL_VISIT_ID = "就诊ID"
COL_MEDICAL_PRODUCT_NAME = "医保目录名称"
COL_MEDICAL_QUANTITY = "数量"
COL_MEDICAL_PRICE = "单价"
COL_MEDICAL_AMOUNT = "明细项目费用总额"
COL_MEDICAL_SETTLEMENT_TIME = "结算时间"
COL_MEDICAL_PERSON_NAME = "人员姓名"
COL_PRESCRIPTION_OUTPATIENT_ID = "门诊号"
COL_PRESCRIPTION_PERSON_NAME = "问诊人姓名"
COL_PRESCRIPTION_SUBMIT_TIME = "提交时间"
COL_PRESCRIPTION_PRODUCT_NAME = "药品名称（通用名）"
COL_PRESCRIPTION_DRUG_CATALOG_PRODUCT_NAME = "商品名称"
COL_IS_PRESCRIPTION_DRUG = "是否处方药"

COLUMN_CONFIG_SHEET = "列名配置"
COLUMN_CONFIG_KEY_COLUMN = "字段代码"
COLUMN_CONFIG_DEFAULT_COLUMN = "默认列名"
COLUMN_CONFIG_USER_COLUMN = "用户录入列名"

QUANTITY_TOLERANCE = 1e-9
AMOUNT_TOLERANCE = 0.1
COMPARE_TIME_TOLERANCE_HOURS = 0.5
SECONDARY_COMPARE_AMOUNT_TOLERANCE = 1
SECONDARY_COMPARE_TIME_TOLERANCE_HOURS = 1
THIRD_COMPARE_AMOUNT_TOLERANCE = 0.01
THIRD_COMPARE_PRODUCT_SIMILARITY_THRESHOLD = 0.75
PRESCRIPTION_COMPARE_TIME_TOLERANCE_HOURS = 1
PRESCRIPTION_PRODUCT_SIMILARITY_THRESHOLD = 0.75
PROGRESS_UPDATE_STEPS = 20
MATCH_STATUS_EXACT = "完全匹配"
MATCH_STATUS_INCOMPLETE = "不完全匹配"
MATCH_STATUS_UNMATCHED = "未匹配"
PRESCRIPTION_STATUS_NORMAL = "正常开方"
PRESCRIPTION_STATUS_AFTER_MEDICINE = "先药后方"
PRESCRIPTION_STATUS_MISSING = "无处方"
PRESCRIPTION_DRUG_MATCHED = "该药品为处方药"
PRESCRIPTION_DRUG_UNMATCHED = "非处方药"
PRESCRIPTION_MATCH_OUTPUT_COLUMNS = [
    "处方端门诊号",
    "处方端问诊人",
    "处方端提交时间",
    "处方端药品名",
    "处方情况",
    "相差时间",
]

COMPARE_OUTPUT_COLUMNS = [
    "医保端编号",
    "销售端对应编号",
    "匹配状态",
    "医保金额",
    "销售金额",
    "医保端对应时间",
    "销售端对应时间",
    "医保端销售商品",
    "销售端销售商品",
    "销售端批准文号",
]


@dataclass(frozen=True)
class OffsetCheckResult:
    output_path: Path
    total_rows: int
    negative_rows: int
    matched_pairs: int
    unmatched_negative_rows: int


@dataclass(frozen=True)
class BillSummary:
    bill_id: str
    total_amount: float
    bill_time: pd.Timestamp
    has_time_component: bool
    items: pd.DataFrame
    source_order: int


@dataclass(frozen=True)
class SalesMedicalCompareResult:
    output_path: Path
    medical_bill_count: int
    matched_bill_count: int
    incomplete_matched_bill_count: int
    third_matched_bill_count: int
    unmatched_bill_count: int
    output_rows: int


@dataclass(frozen=True)
class PrescriptionMedicalCompareResult:
    output_path: Path
    total_rows: int
    normal_rows: int
    after_medicine_rows: int
    missing_rows: int
    prescription_drug_rows: int
    non_prescription_drug_rows: int


@dataclass(frozen=True)
class ColumnConfig:
    sales_bill_date: str = COL_BILL_DATE
    sales_product_name: str = COL_PRODUCT_NAME
    sales_price: str = COL_PRICE
    sales_quantity: str = COL_QUANTITY
    sales_amount: str = COL_AMOUNT
    sales_approval_no: str = COL_APPROVAL_NO
    sales_offset_id: str = COL_OFFSET_ID
    sales_order_id: str = COL_SALES_ORDER_ID
    medical_visit_id: str = COL_MEDICAL_VISIT_ID
    medical_product_name: str = COL_MEDICAL_PRODUCT_NAME
    medical_quantity: str = COL_MEDICAL_QUANTITY
    medical_price: str = COL_MEDICAL_PRICE
    medical_amount: str = COL_MEDICAL_AMOUNT
    medical_settlement_time: str = COL_MEDICAL_SETTLEMENT_TIME
    medical_person_name: str = COL_MEDICAL_PERSON_NAME
    prescription_outpatient_id: str = COL_PRESCRIPTION_OUTPATIENT_ID
    prescription_person_name: str = COL_PRESCRIPTION_PERSON_NAME
    prescription_submit_time: str = COL_PRESCRIPTION_SUBMIT_TIME
    prescription_product_name: str = COL_PRESCRIPTION_PRODUCT_NAME

    @property
    def return_required_columns(self) -> list[str]:
        return [
            self.sales_bill_date,
            self.sales_product_name,
            self.sales_price,
            self.sales_quantity,
            self.sales_amount,
            self.sales_approval_no,
        ]

    @property
    def sales_compare_required_columns(self) -> list[str]:
        return [
            self.sales_order_id,
            self.sales_bill_date,
            self.sales_product_name,
            self.sales_amount,
            self.sales_approval_no,
        ]

    @property
    def medical_compare_required_columns(self) -> list[str]:
        return [
            self.medical_visit_id,
            self.medical_product_name,
            self.medical_quantity,
            self.medical_price,
            self.medical_amount,
            self.medical_settlement_time,
        ]

    @property
    def prescription_medical_required_columns(self) -> list[str]:
        return [
            self.medical_person_name,
            self.medical_settlement_time,
            self.medical_product_name,
        ]

    @property
    def prescription_required_columns(self) -> list[str]:
        return [
            self.prescription_outpatient_id,
            self.prescription_person_name,
            self.prescription_submit_time,
            self.prescription_product_name,
        ]


DEFAULT_COLUMN_CONFIG = ColumnConfig()

COLUMN_CONFIG_FIELDS: dict[str, tuple[str, str, str, str, str]] = {
    "sales_bill_date": (
        "销售端",
        "销售时间",
        ColumnConfig.sales_bill_date,
        "退货冲销检查、销售端与医保端比对",
        "如果销售端只有日期，程序会按同一天匹配；如果有时分秒，按小时误差规则匹配。",
    ),
    "sales_product_name": (
        "销售端",
        "商品名称",
        ColumnConfig.sales_product_name,
        "退货冲销检查、销售端与医保端比对",
        "",
    ),
    "sales_price": (
        "销售端",
        "销售单价",
        ColumnConfig.sales_price,
        "退货冲销检查",
        "",
    ),
    "sales_quantity": (
        "销售端",
        "销售数量",
        ColumnConfig.sales_quantity,
        "退货冲销检查",
        "",
    ),
    "sales_amount": (
        "销售端",
        "销售金额",
        ColumnConfig.sales_amount,
        "退货冲销检查、销售端与医保端比对",
        "",
    ),
    "sales_approval_no": (
        "销售端",
        "批准文号",
        ColumnConfig.sales_approval_no,
        "退货冲销检查、销售端与医保端比对",
        "",
    ),
    "sales_offset_id": (
        "销售端",
        "冲销编号输出列",
        ColumnConfig.sales_offset_id,
        "退货冲销检查",
        "输出时会新增或覆盖此列。",
    ),
    "sales_order_id": (
        "销售端",
        "销售单号/流水号",
        ColumnConfig.sales_order_id,
        "销售端与医保端比对",
        "",
    ),
    "medical_visit_id": (
        "医保端",
        "就诊 ID",
        ColumnConfig.medical_visit_id,
        "销售端与医保端比对",
        "",
    ),
    "medical_product_name": (
        "医保端",
        "医保商品名称",
        ColumnConfig.medical_product_name,
        "销售端与医保端比对、处方端与医保端比对",
        "",
    ),
    "medical_quantity": (
        "医保端",
        "医保数量",
        ColumnConfig.medical_quantity,
        "销售端与医保端比对",
        "",
    ),
    "medical_price": (
        "医保端",
        "医保单价",
        ColumnConfig.medical_price,
        "销售端与医保端比对",
        "",
    ),
    "medical_amount": (
        "医保端",
        "医保金额",
        ColumnConfig.medical_amount,
        "销售端与医保端比对",
        "",
    ),
    "medical_settlement_time": (
        "医保端",
        "医保结算时间",
        ColumnConfig.medical_settlement_time,
        "销售端与医保端比对、处方端与医保端比对",
        "",
    ),
    "medical_person_name": (
        "医保端",
        "人员姓名",
        ColumnConfig.medical_person_name,
        "处方端与医保端比对",
        "",
    ),
    "prescription_outpatient_id": (
        "处方端",
        "门诊号",
        ColumnConfig.prescription_outpatient_id,
        "处方端与医保端比对",
        "匹配成功后输出到医保端结果的处方端门诊号列。",
    ),
    "prescription_person_name": (
        "处方端",
        "问诊人姓名",
        ColumnConfig.prescription_person_name,
        "处方端与医保端比对",
        "",
    ),
    "prescription_submit_time": (
        "处方端",
        "提交时间",
        ColumnConfig.prescription_submit_time,
        "处方端与医保端比对",
        "",
    ),
    "prescription_product_name": (
        "处方端",
        "药品名称（通用名）",
        ColumnConfig.prescription_product_name,
        "处方端与医保端比对",
        "处方端药品名可比医保端更复杂，程序会做模糊匹配。",
    ),
}


def validate_required_columns(df: pd.DataFrame, required_columns: Iterable[str]) -> None:
    """Raise a clear error if the input file is missing required columns."""
    missing_columns = [column for column in required_columns if column not in df.columns]
    if missing_columns:
        missing = "、".join(missing_columns)
        raise ValueError(f"输入表缺少必要列：{missing}")


def load_column_config(config_path: Path) -> ColumnConfig:
    """Load user-entered column names from the column config workbook."""
    if not config_path.exists():
        raise FileNotFoundError(f"未找到列名配置文件：{config_path}")

    try:
        df = pd.read_excel(config_path, sheet_name=COLUMN_CONFIG_SHEET)
    except ValueError:
        df = pd.read_excel(config_path)

    validate_required_columns(
        df,
        [COLUMN_CONFIG_KEY_COLUMN, COLUMN_CONFIG_DEFAULT_COLUMN, COLUMN_CONFIG_USER_COLUMN],
    )

    configured_columns = {}
    for _, row in df.iterrows():
        field_key = _text_value(row[COLUMN_CONFIG_KEY_COLUMN])
        if field_key not in COLUMN_CONFIG_FIELDS:
            continue

        user_column = _text_value(row[COLUMN_CONFIG_USER_COLUMN])
        default_column = _text_value(row[COLUMN_CONFIG_DEFAULT_COLUMN])
        configured_columns[field_key] = user_column or default_column

    return ColumnConfig(
        **{
            field_key: configured_columns.get(
                field_key,
                getattr(DEFAULT_COLUMN_CONFIG, field_key),
            )
            for field_key in COLUMN_CONFIG_FIELDS
        }
    )


def load_sales_data(input_path: Path, column_config: ColumnConfig) -> pd.DataFrame:
    """Load the sales detail Excel file."""
    if not input_path.exists():
        raise FileNotFoundError(f"未找到输入文件：{input_path}")

    df = pd.read_excel(input_path)
    validate_required_columns(df, column_config.return_required_columns)
    return df


def load_compare_sales_data(input_path: Path, column_config: ColumnConfig) -> pd.DataFrame:
    """Load the sales-side workbook used by the sales/medical comparison."""
    if not input_path.exists():
        raise FileNotFoundError(f"未找到销售端文件：{input_path}")

    df = pd.read_excel(input_path)
    validate_required_columns(df, column_config.sales_compare_required_columns)
    return df


def _read_csv_with_common_encodings(input_path: Path) -> pd.DataFrame:
    """Read a CSV file, trying common Chinese CSV encodings."""
    if not input_path.exists():
        raise FileNotFoundError(f"未找到 CSV 文件：{input_path}")

    last_error: Exception | None = None
    for encoding in ("utf-8-sig", "utf-8", "gb18030"):
        try:
            return pd.read_csv(input_path, encoding=encoding)
        except UnicodeDecodeError as exc:
            last_error = exc

    raise ValueError(f"无法读取 CSV，请检查文件编码：{last_error}")


def load_compare_medical_data(input_path: Path, column_config: ColumnConfig) -> pd.DataFrame:
    """Load the medical-side CSV used by the sales/medical comparison."""
    if not input_path.exists():
        raise FileNotFoundError(f"未找到医保端文件：{input_path}")

    df = _read_csv_with_common_encodings(input_path)
    validate_required_columns(df, column_config.medical_compare_required_columns)
    return df


def load_prescription_data(input_path: Path, column_config: ColumnConfig) -> pd.DataFrame:
    """Load the prescription-side workbook used by the prescription/medical comparison."""
    if not input_path.exists():
        raise FileNotFoundError(f"未找到处方明细文件：{input_path}")

    df = pd.read_excel(input_path)
    validate_required_columns(df, column_config.prescription_required_columns)
    return df


def load_prescription_medical_data(input_path: Path, column_config: ColumnConfig) -> pd.DataFrame:
    """Load the medical-side CSV used by the prescription/medical comparison."""
    if not input_path.exists():
        raise FileNotFoundError(f"未找到医保端文件：{input_path}")

    df = _read_csv_with_common_encodings(input_path)
    validate_required_columns(df, column_config.prescription_medical_required_columns)
    return df


def load_prescription_drug_catalog(input_path: Path) -> pd.DataFrame:
    """Load the fixed-format prescription-drug catalog workbook."""
    if not input_path.exists():
        raise FileNotFoundError(f"未找到处方药目录文件：{input_path}")

    df = pd.read_excel(input_path)
    validate_required_columns(df, [COL_PRESCRIPTION_DRUG_CATALOG_PRODUCT_NAME])
    return df


def _numeric_series(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce")


def _date_series(series: pd.Series) -> pd.Series:
    return pd.to_datetime(series, errors="coerce")


def _value_has_time_component(value: object) -> bool:
    if pd.isna(value): # type: ignore
        return False

    text = str(value).strip()
    if re.search(r"\d{1,2}:\d{2}", text):
        parsed = pd.to_datetime(value, errors="coerce") # type: ignore
        if pd.isna(parsed):
            return True
        timestamp = pd.Timestamp(parsed)
        return any(
            [
                timestamp.hour,
                timestamp.minute,
                timestamp.second,
                timestamp.microsecond,
                timestamp.nanosecond,
            ]
        )

    parsed = pd.to_datetime(value, errors="coerce") # type: ignore
    if pd.isna(parsed):
        return False

    timestamp = pd.Timestamp(parsed)
    return any(
        [
            timestamp.hour,
            timestamp.minute,
            timestamp.second,
            timestamp.microsecond,
            timestamp.nanosecond,
        ]
    )


def _same_quantity(quantity: pd.Series, target_quantity: float) -> pd.Series:
    return (quantity - target_quantity).abs() <= QUANTITY_TOLERANCE


def _safe_abs_diff(left: float, right: float) -> float:
    if pd.isna(left) or pd.isna(right):
        return float("inf")
    return abs(float(left) - float(right))


def _date_distance_days(left: pd.Timestamp, right: pd.Timestamp) -> float:
    if pd.isna(left) or pd.isna(right):
        return float("inf")
    left_date = pd.Timestamp(left).normalize()
    right_date = pd.Timestamp(right).normalize()
    return abs((left_date - right_date).days)


def _time_distance_hours(left: pd.Timestamp, right: pd.Timestamp) -> float:
    if pd.isna(left) or pd.isna(right):
        return float("inf")
    return abs((pd.Timestamp(left) - pd.Timestamp(right)).total_seconds() / 3600)


def _same_date(left: pd.Timestamp, right: pd.Timestamp) -> bool:
    if pd.isna(left) or pd.isna(right):
        return False
    return pd.Timestamp(left).normalize() == pd.Timestamp(right).normalize()


def _sales_time_match_distance(
    medical_bill: BillSummary,
    sales_bill: BillSummary,
    tolerance_hours: float,
) -> tuple[bool, float]:
    if not sales_bill.has_time_component:
        return _same_date(medical_bill.bill_time, sales_bill.bill_time), 0.0

    time_distance_hours = _time_distance_hours(medical_bill.bill_time, sales_bill.bill_time)
    return time_distance_hours <= tolerance_hours, time_distance_hours


def _amount_key(amount: float) -> str:
    return f"{round(float(amount), 2):.2f}"


def _same_amount(
    left: float,
    right: float,
    tolerance: float = AMOUNT_TOLERANCE,
) -> bool:
    if pd.isna(left) or pd.isna(right):
        return False
    return abs(float(left) - float(right)) <= tolerance


def _text_value(value: object) -> str:
    if pd.isna(value): # type: ignore
        return ""
    return str(value).strip()


def _show_progress(label: str, current: int, total: int) -> None:
    """Print progress at roughly five-percent intervals without flooding the console."""
    if total <= 0:
        print(f"{label}：无待处理数据", flush=True)
        return

    interval = max(1, total // PROGRESS_UPDATE_STEPS)
    if current == 1 or current == total or current % interval == 0:
        percent = current * 100 / total
        print(f"{label}：{current}/{total}（{percent:.1f}%）", flush=True)


def _normalize_product_name(value: object) -> str:
    text = _text_value(value).lower()
    return re.sub(r"[\s（）()\[\]【】、，,。.;；:：\-_/\\·]+", "", text)


def _is_generic_medical_supply_name(value: object) -> bool:
    text = _text_value(value)
    return "械字号" in text or "消字号" in text


def _normalize_prescription_drug_name(value: object, remove_parenthetical: bool = False) -> str:
    text = _text_value(value).lower()
    if remove_parenthetical:
        previous = None
        while previous != text:
            previous = text
            text = re.sub(r"[（(\[【][^）)\]】]*[）)\]】]", "", text)
    return re.sub(r"[\s（）()\[\]【】、，,。.;；:：\-_/\\·]+", "", text)


def _prescription_drug_name_matches(
    medical_name: object,
    catalog_full_names: set[str],
    catalog_base_names: set[str],
) -> bool:
    medical_full_name = _normalize_prescription_drug_name(medical_name)
    medical_base_name = _normalize_prescription_drug_name(
        medical_name,
        remove_parenthetical=True,
    )
    if not medical_full_name:
        return False

    if medical_full_name in catalog_full_names or medical_base_name in catalog_base_names:
        return True

    for catalog_name in catalog_base_names:
        shorter_length = min(len(medical_base_name), len(catalog_name))
        longer_length = max(len(medical_base_name), len(catalog_name))
        if shorter_length < 4 or shorter_length / longer_length < 0.6:
            continue
        if medical_base_name in catalog_name or catalog_name in medical_base_name:
            return True

    return False


def _product_similarity(left: object, right: object) -> float:
    if _is_generic_medical_supply_name(left):
        return 1.0
    return _product_similarity_normalized(
        _normalize_product_name(left),
        _normalize_product_name(right),
    )


def _product_similarity_normalized(left_text: str, right_text: str) -> float:
    if not left_text or not right_text:
        return 0.0
    if left_text in right_text or right_text in left_text:
        shorter = min(len(left_text), len(right_text))
        longer = max(len(left_text), len(right_text))
        return 0.8 + 0.2 * (shorter / longer)
    return SequenceMatcher(None, left_text, right_text).ratio()


def _bill_product_similarity(
    medical_bill: BillSummary,
    sales_bill: BillSummary,
    column_config: ColumnConfig,
) -> float:
    medical_names = [
        _text_value(value)
        for value in medical_bill.items[column_config.medical_product_name]
    ]
    sales_names = [
        _text_value(value)
        for value in sales_bill.items[column_config.sales_product_name]
    ]
    if not medical_names or not sales_names:
        return 0.0

    scores = []
    for medical_name in medical_names:
        scores.append(max(_product_similarity(medical_name, sales_name) for sales_name in sales_names))
    return sum(scores) / len(scores)


def _amount_index_candidates(
    amount: float,
    sales_amount_index: dict[str, list[BillSummary]],
    tolerance: float,
) -> list[BillSummary]:
    if pd.isna(amount):
        return []
    center_cents = round(float(amount) * 100)
    tolerance_cents = max(0, int(round(tolerance * 100)))
    candidates = []
    seen_bill_ids: set[str] = set()
    for cents in range(center_cents - tolerance_cents, center_cents + tolerance_cents + 1):
        for sales_bill in sales_amount_index.get(f"{cents / 100:.2f}", []):
            if sales_bill.bill_id not in seen_bill_ids:
                candidates.append(sales_bill)
                seen_bill_ids.add(sales_bill.bill_id)
    return candidates


def _summarize_bills(
    df: pd.DataFrame,
    bill_id_column: str,
    amount_column: str,
    time_column: str,
) -> list[BillSummary]:
    working_df = df.copy()
    working_df["_analysis_bill_id"] = working_df[bill_id_column].map(_text_value)
    working_df["_analysis_amount"] = _numeric_series(working_df[amount_column])
    working_df["_analysis_time"] = _date_series(working_df[time_column])
    working_df = working_df[working_df["_analysis_bill_id"] != ""]

    summaries: list[BillSummary] = []
    for bill_id, group in working_df.groupby("_analysis_bill_id", sort=False):
        total_amount = group["_analysis_amount"].sum()
        valid_times = group["_analysis_time"].dropna()
        bill_time = valid_times.iloc[0] if not valid_times.empty else pd.NaT
        has_time_component = any(_value_has_time_component(value) for value in group[time_column])
        summaries.append(
            BillSummary(
                bill_id=bill_id, # type: ignore
                total_amount=float(total_amount),
                bill_time=bill_time, # type: ignore
                has_time_component=has_time_component,
                items=group.drop(
                    columns=["_analysis_bill_id", "_analysis_amount", "_analysis_time"]
                ),
                source_order=int(group.index.min()),
            )
        )
    return summaries


def _sales_bill_amount_index(sales_bills: list[BillSummary]) -> dict[str, list[BillSummary]]:
    index: dict[str, list[BillSummary]] = {}
    for sales_bill in sales_bills:
        index.setdefault(_amount_key(sales_bill.total_amount), []).append(sales_bill)
    return index


def _sales_bill_time_indexes(
    sales_bills: list[BillSummary],
) -> tuple[
    dict[pd.Timestamp, list[BillSummary]],
    dict[pd.Timestamp, list[BillSummary]],
]:
    """Index date-only bills by date and timed bills by hour for secondary matching."""
    date_index: dict[pd.Timestamp, list[BillSummary]] = {}
    hour_index: dict[pd.Timestamp, list[BillSummary]] = {}
    for sales_bill in sales_bills:
        if pd.isna(sales_bill.bill_time):
            continue
        bill_time = pd.Timestamp(sales_bill.bill_time)
        if sales_bill.has_time_component:
            hour_index.setdefault(bill_time.floor("h"), []).append(sales_bill)
        else:
            date_index.setdefault(bill_time.normalize(), []).append(sales_bill)
    return date_index, hour_index


def _secondary_sales_candidates(
    medical_bill: BillSummary,
    sales_date_index: dict[pd.Timestamp, list[BillSummary]],
    sales_hour_index: dict[pd.Timestamp, list[BillSummary]],
) -> list[BillSummary]:
    medical_time = pd.Timestamp(medical_bill.bill_time)
    candidates = list(sales_date_index.get(medical_time.normalize(), []))
    medical_hour = medical_time.floor("h")
    tolerance = int(SECONDARY_COMPARE_TIME_TOLERANCE_HOURS)
    for hour_offset in range(-tolerance, tolerance + 1):
        candidate_hour = medical_hour + pd.Timedelta(hours=hour_offset)
        candidates.extend(sales_hour_index.get(candidate_hour, []))
    return candidates


def _find_best_sales_bill_match(
    medical_bill: BillSummary,
    sales_amount_index: dict[str, list[BillSummary]],
    used_sales_bill_ids: set[str],
    column_config: ColumnConfig,
) -> BillSummary | None:
    candidates = []
    for sales_bill in _amount_index_candidates(
        medical_bill.total_amount,
        sales_amount_index,
        AMOUNT_TOLERANCE,
    ):
        if sales_bill.bill_id in used_sales_bill_ids:
            continue
        if not _same_amount(medical_bill.total_amount, sales_bill.total_amount):
            continue

        is_time_match, time_distance = _sales_time_match_distance(
            medical_bill,
            sales_bill,
            COMPARE_TIME_TOLERANCE_HOURS,
        )
        if not is_time_match:
            continue

        candidates.append((sales_bill, time_distance))

    if not candidates:
        return None

    nearest_time_distance = min(time_distance for _, time_distance in candidates)
    nearest_candidates = [
        sales_bill
        for sales_bill, time_distance in candidates
        if time_distance == nearest_time_distance
    ]

    def sort_key(sales_bill: BillSummary) -> tuple[float, int]:
        return (
            -_bill_product_similarity(medical_bill, sales_bill, column_config),
            sales_bill.source_order,
        )

    return min(nearest_candidates, key=sort_key)


def _find_best_secondary_sales_bill_match(
    medical_bill: BillSummary,
    sales_date_index: dict[pd.Timestamp, list[BillSummary]],
    sales_hour_index: dict[pd.Timestamp, list[BillSummary]],
    used_sales_bill_ids: set[str],
    column_config: ColumnConfig,
) -> BillSummary | None:
    if pd.isna(medical_bill.bill_time):
        return None

    candidates = []
    for sales_bill in _secondary_sales_candidates(
        medical_bill,
        sales_date_index,
        sales_hour_index,
    ):
        if sales_bill.bill_id in used_sales_bill_ids:
            continue

        amount_distance = _safe_abs_diff(
            medical_bill.total_amount,
            sales_bill.total_amount,
        )
        if amount_distance > SECONDARY_COMPARE_AMOUNT_TOLERANCE:
            continue

        is_time_match, time_distance = _sales_time_match_distance(
            medical_bill,
            sales_bill,
            SECONDARY_COMPARE_TIME_TOLERANCE_HOURS,
        )
        if not is_time_match:
            continue

        product_similarity = _bill_product_similarity(
            medical_bill,
            sales_bill,
            column_config,
        )
        candidates.append(
            (sales_bill, amount_distance, time_distance, product_similarity)
        )

    if not candidates:
        return None

    def sort_key(
        candidate: tuple[BillSummary, float, float, float],
    ) -> tuple[float, float, float, int]:
        sales_bill, amount_distance, time_distance_hours, product_similarity = candidate
        return (
            amount_distance,
            time_distance_hours,
            -product_similarity,
            sales_bill.source_order,
        )

    return min(candidates, key=sort_key)[0]


def _find_best_third_sales_bill_match(
    medical_bill: BillSummary,
    sales_amount_index: dict[str, list[BillSummary]],
    used_sales_bill_ids: set[str],
    column_config: ColumnConfig,
) -> BillSummary | None:
    candidates = []
    for sales_bill in _amount_index_candidates(
        medical_bill.total_amount,
        sales_amount_index,
        THIRD_COMPARE_AMOUNT_TOLERANCE,
    ):
        if sales_bill.bill_id in used_sales_bill_ids:
            continue
        if not _same_amount(
            medical_bill.total_amount,
            sales_bill.total_amount,
            THIRD_COMPARE_AMOUNT_TOLERANCE,
        ):
            continue
        product_similarity = _bill_product_similarity(
            medical_bill,
            sales_bill,
            column_config,
        )
        if product_similarity < THIRD_COMPARE_PRODUCT_SIMILARITY_THRESHOLD:
            continue
        candidates.append((sales_bill, product_similarity))

    if not candidates:
        return None
    return min(
        candidates,
        key=lambda candidate: (-candidate[1], candidate[0].source_order),
    )[0]


def _sales_item_records(
    sales_bill: BillSummary,
    column_config: ColumnConfig,
) -> list[dict[str, str]]:
    records = []
    for _, row in sales_bill.items.iterrows():
        records.append(
            {
                "name": _text_value(row[column_config.sales_product_name]),
                "approval_no": _text_value(row[column_config.sales_approval_no]),
            }
        )
    return records


def _align_sales_items_to_medical(
    medical_names: list[str],
    sales_items: list[dict[str, str]],
) -> list[dict[str, str] | None]:
    aligned: list[dict[str, str] | None] = []
    used_sales_indices: set[int] = set()

    for medical_name in medical_names:
        available_indices = [
            index for index in range(len(sales_items)) if index not in used_sales_indices
        ]
        if not available_indices:
            aligned.append(None)
            continue

        best_index = max(
            available_indices,
            key=lambda index: (
                _product_similarity(medical_name, sales_items[index]["name"]),
                -index,
            ),
        )
        used_sales_indices.add(best_index)
        aligned.append(sales_items[best_index])

    for index, sales_item in enumerate(sales_items):
        if index not in used_sales_indices:
            aligned.append(sales_item)

    return aligned


def _build_compare_rows(
    medical_bill: BillSummary,
    sales_bill: BillSummary | None,
    match_status: str,
    column_config: ColumnConfig,
) -> list[dict[str, object]]:
    medical_names = [
        _text_value(value)
        for value in medical_bill.items[column_config.medical_product_name]
    ]

    if sales_bill is None:
        row_count = max(len(medical_names), 1)
        return [
            {
                "医保端编号": medical_bill.bill_id,
                "销售端对应编号": "销售端无对应编号",
                "匹配状态": MATCH_STATUS_UNMATCHED,
                "医保金额": round(medical_bill.total_amount, 2),
                "销售金额": "",
                "医保端对应时间": medical_bill.bill_time,
                "销售端对应时间": "",
                "医保端销售商品": medical_names[index] if index < len(medical_names) else "",
                "销售端销售商品": "",
                "销售端批准文号": "",
            }
            for index in range(row_count)
        ]

    sales_items = _sales_item_records(sales_bill, column_config)
    aligned_sales_items = _align_sales_items_to_medical(medical_names, sales_items)
    row_count = max(len(medical_names), len(aligned_sales_items), 1)
    rows = []

    for index in range(row_count):
        sales_item = aligned_sales_items[index] if index < len(aligned_sales_items) else None
        rows.append(
            {
                "医保端编号": medical_bill.bill_id,
                "销售端对应编号": sales_bill.bill_id,
                "匹配状态": match_status,
                "医保金额": round(medical_bill.total_amount, 2),
                "销售金额": round(sales_bill.total_amount, 2),
                "医保端对应时间": medical_bill.bill_time,
                "销售端对应时间": sales_bill.bill_time,
                "医保端销售商品": medical_names[index] if index < len(medical_names) else "",
                "销售端销售商品": sales_item["name"] if sales_item else "",
                "销售端批准文号": sales_item["approval_no"] if sales_item else "",
            }
        )

    return rows


def _format_time_difference(left: pd.Timestamp, right: pd.Timestamp) -> str:
    if pd.isna(left) or pd.isna(right):
        return ""

    total_minutes = int(abs((pd.Timestamp(left) - pd.Timestamp(right)).total_seconds()) // 60)
    hours, minutes = divmod(total_minutes, 60)
    if hours and minutes:
        return f"{hours}小时{minutes}分钟"
    if hours:
        return f"{hours}小时"
    return f"{minutes}分钟"


def _find_best_prescription_match(
    medical_row: pd.Series,
    medical_time: pd.Timestamp,
    prescription_lookup: dict[str, pd.DataFrame],
    used_prescription_indices: set[object],
    column_config: ColumnConfig,
) -> object | None:
    medical_person_name = _text_value(medical_row[column_config.medical_person_name])
    medical_product_name = _normalize_product_name(medical_row[column_config.medical_product_name])

    if not medical_person_name or pd.isna(medical_time):
        return None

    person_prescriptions = prescription_lookup.get(medical_person_name)
    if person_prescriptions is None or person_prescriptions.empty:
        return None

    available_prescriptions = person_prescriptions[
        ~person_prescriptions.index.isin(used_prescription_indices)
    ]
    if available_prescriptions.empty:
        return None

    time_distances = (
        pd.Timestamp(medical_time) - available_prescriptions["_prescription_submit_time"]
    ).abs().dt.total_seconds() / 3600
    available_prescriptions = available_prescriptions[
        time_distances <= PRESCRIPTION_COMPARE_TIME_TOLERANCE_HOURS
    ]
    if available_prescriptions.empty:
        return None

    candidates = []
    for prescription_index, prescription_row in available_prescriptions.iterrows():
        product_similarity = _product_similarity_normalized(
            medical_product_name,
            prescription_row["_prescription_product_name"],
        )
        if product_similarity < PRESCRIPTION_PRODUCT_SIMILARITY_THRESHOLD:
            continue

        candidates.append(
            (
                prescription_index,
                -product_similarity,
                time_distances.at[prescription_index],
                prescription_row["_prescription_source_order"],
            )
        )

    if not candidates:
        return None

    return min(candidates, key=lambda candidate: candidate[1:])[0]


def _build_prescription_lookup(
    prescription_df: pd.DataFrame,
    prescription_times: pd.Series,
    column_config: ColumnConfig,
) -> dict[str, pd.DataFrame]:
    lookup_df = pd.DataFrame(
        {
            "_prescription_person_name": prescription_df[
                column_config.prescription_person_name
            ].map(_text_value),
            "_prescription_submit_time": prescription_times,
            "_prescription_product_name": prescription_df[
                column_config.prescription_product_name
            ].map(_normalize_product_name),
            "_prescription_source_order": range(len(prescription_df)),
        },
        index=prescription_df.index,
    )
    lookup_df = lookup_df[
        (lookup_df["_prescription_person_name"] != "")
        & lookup_df["_prescription_submit_time"].notna()
        & (lookup_df["_prescription_product_name"] != "")
    ]
    return {
        person_name: person_df
        for person_name, person_df in lookup_df.groupby("_prescription_person_name", sort=False)
    } # type: ignore


def compare_prescriptions_to_medical(
    medical_df: pd.DataFrame,
    prescription_df: pd.DataFrame,
    column_config: ColumnConfig,
) -> tuple[pd.DataFrame, int, int, int]:
    """
    Mark each medical-side row with its prescription status.

    Matching rule:
    1. Medical person name equals prescription person name.
    2. Settlement time and prescription submit time are within 1 hour.
    3. Medical product name and prescription product name are similar enough.
    """
    validate_required_columns(medical_df, column_config.prescription_medical_required_columns)
    validate_required_columns(prescription_df, column_config.prescription_required_columns)

    result_df = medical_df.copy()
    original_medical_columns = [
        column
        for column in result_df.columns
        if column not in PRESCRIPTION_MATCH_OUTPUT_COLUMNS
    ]
    for column in PRESCRIPTION_MATCH_OUTPUT_COLUMNS:
        result_df[column] = ""
    result_df["处方情况"] = PRESCRIPTION_STATUS_MISSING

    prescription_times = _date_series(prescription_df[column_config.prescription_submit_time])
    medical_times = _date_series(result_df[column_config.medical_settlement_time])
    prescription_lookup = _build_prescription_lookup(
        prescription_df,
        prescription_times,
        column_config,
    )
    used_prescription_indices: set[object] = set()
    normal_rows = 0
    after_medicine_rows = 0

    total_medical_rows = len(result_df)
    for progress_index, (medical_index, medical_row) in enumerate(
        result_df.iterrows(),
        start=1,
    ):
        prescription_index = _find_best_prescription_match(
            medical_row,
            medical_times.at[medical_index], # type: ignore
            prescription_lookup,
            used_prescription_indices,
            column_config,
        )
        if prescription_index is None:
            _show_progress("处方医保比对进度", progress_index, total_medical_rows)
            continue

        used_prescription_indices.add(prescription_index)
        medical_time = medical_times.at[medical_index]
        prescription_time = prescription_times.at[prescription_index]
        result_df.at[medical_index, "处方端门诊号"] = prescription_df.at[
            prescription_index,
            column_config.prescription_outpatient_id,
        ]
        result_df.at[medical_index, "处方端问诊人"] = prescription_df.at[
            prescription_index,
            column_config.prescription_person_name,
        ]
        result_df.at[medical_index, "处方端提交时间"] = prescription_df.at[
            prescription_index,
            column_config.prescription_submit_time,
        ]
        result_df.at[medical_index, "处方端药品名"] = prescription_df.at[
            prescription_index,
            column_config.prescription_product_name,
        ]

        if pd.Timestamp(medical_time) < pd.Timestamp(prescription_time): # type: ignore
            result_df.at[medical_index, "处方情况"] = PRESCRIPTION_STATUS_AFTER_MEDICINE
            result_df.at[medical_index, "相差时间"] = _format_time_difference(
                medical_time, # type: ignore
                prescription_time, # type: ignore
            )
            after_medicine_rows += 1
        else:
            result_df.at[medical_index, "处方情况"] = PRESCRIPTION_STATUS_NORMAL
            normal_rows += 1

        _show_progress("处方医保比对进度", progress_index, total_medical_rows)

    missing_rows = int((result_df["处方情况"] == PRESCRIPTION_STATUS_MISSING).sum())
    result_df = result_df[original_medical_columns + PRESCRIPTION_MATCH_OUTPUT_COLUMNS]
    return result_df, normal_rows, after_medicine_rows, missing_rows


def compare_medical_sales_to_prescription_drugs(
    medical_df: pd.DataFrame,
    catalog_df: pd.DataFrame,
    medical_product_column: str = COL_MEDICAL_PRODUCT_NAME,
) -> tuple[pd.DataFrame, int, int]:
    """
    Mark whether each medical-side product is listed in the prescription-drug catalog.

    Product names are normalized before matching. Parenthetical brand or manufacturer
    suffixes are ignored, while the main drug name and dosage form remain significant.
    """
    validate_required_columns(medical_df, [medical_product_column])
    validate_required_columns(catalog_df, [COL_PRESCRIPTION_DRUG_CATALOG_PRODUCT_NAME])

    catalog_names = catalog_df[COL_PRESCRIPTION_DRUG_CATALOG_PRODUCT_NAME].dropna()
    catalog_full_names = {
        normalized_name
        for value in catalog_names
        if (normalized_name := _normalize_prescription_drug_name(value))
    }
    catalog_base_names = {
        normalized_name
        for value in catalog_names
        if (
            normalized_name := _normalize_prescription_drug_name(
                value,
                remove_parenthetical=True,
            )
        )
    }

    result_df = medical_df.copy()
    match_results = []
    total_medical_rows = len(result_df)
    for progress_index, value in enumerate(
        result_df[medical_product_column],
        start=1,
    ):
        match_results.append(
            _prescription_drug_name_matches(
                value,
                catalog_full_names,
                catalog_base_names,
            )
        )
        _show_progress("处方药目录比对进度", progress_index, total_medical_rows)
    matched_mask = pd.Series(match_results, index=result_df.index, dtype=bool)
    result_df[COL_IS_PRESCRIPTION_DRUG] = matched_mask.map(
        {
            True: PRESCRIPTION_DRUG_MATCHED,
            False: PRESCRIPTION_DRUG_UNMATCHED,
        }
    )

    prescription_drug_rows = int(matched_mask.sum())
    non_prescription_drug_rows = len(result_df) - prescription_drug_rows
    return result_df, prescription_drug_rows, non_prescription_drug_rows


def _approval_mismatch(left: object, right: object) -> int:
    if pd.isna(left) or pd.isna(right):# type: ignore
        return 1
    return 0 if str(left).strip() == str(right).strip() else 1


def build_column_config_template_rows() -> list[dict[str, str]]:
    rows = []
    for field_key, (
        source_side,
        field_name,
        default_column,
        used_by,
        note,
    ) in COLUMN_CONFIG_FIELDS.items():
        rows.append(
            {
                COLUMN_CONFIG_KEY_COLUMN: field_key,
                "数据来源": source_side,
                "字段含义": field_name,
                COLUMN_CONFIG_DEFAULT_COLUMN: default_column,
                COLUMN_CONFIG_USER_COLUMN: default_column,
                "适用功能": used_by,
                "说明": note,
            }
        )
    return rows


def create_column_config_template(output_path: Path) -> Path:
    """Create an editable workbook for mapping actual input headers."""
    result_df = pd.DataFrame(build_column_config_template_rows())
    result_df.to_excel(output_path, sheet_name=COLUMN_CONFIG_SHEET, index=False)
    # 用户只需要修改“用户录入列名”，用红色粗体表头突出唯一编辑入口。
    workbook = load_workbook(output_path)
    worksheet = workbook[COLUMN_CONFIG_SHEET]
    user_column_index = list(result_df.columns).index(COLUMN_CONFIG_USER_COLUMN) + 1
    worksheet.cell(row=1, column=user_column_index).font = Font(
        color="FFFF0000",
        bold=True,
    )
    workbook.save(output_path)
    return output_path


def _find_best_positive_match(
    df: pd.DataFrame,
    quantities: pd.Series,
    dates: pd.Series,
    prices: pd.Series,
    amounts: pd.Series,
    negative_index: int,
    used_positive_indices: set[int],
    column_config: ColumnConfig,
) -> int | None:
    negative_quantity = quantities.at[negative_index]
    if pd.isna(negative_quantity):
        return None

    target_quantity = abs(float(negative_quantity))# type: ignore
    product_name = df.at[negative_index, column_config.sales_product_name]

    candidates = df.index[
        (df[column_config.sales_product_name] == product_name)
        & (quantities > 0)
        & _same_quantity(quantities, target_quantity)
    ]
    candidates = [index for index in candidates if index not in used_positive_indices]
    if not candidates:
        return None

    negative_date = dates.at[negative_index]
    negative_price = prices.at[negative_index]
    negative_amount_abs = abs(amounts.at[negative_index]) if not pd.isna(amounts.at[negative_index]) else float("nan")# type: ignore
    negative_approval_no = df.at[negative_index, column_config.sales_approval_no]

    def sort_key(candidate_index: int) -> tuple[float, int, float, float, int]:
        return (
            _date_distance_days(negative_date, dates.at[candidate_index]), # type: ignore
            _approval_mismatch(
                negative_approval_no,
                df.at[candidate_index, column_config.sales_approval_no],
            ),
            _safe_abs_diff(negative_price, prices.at[candidate_index]),# type: ignore
            _safe_abs_diff(negative_amount_abs, amounts.at[candidate_index]),# type: ignore
            int(candidate_index),
        )

    return min(candidates, key=sort_key)


def mark_return_offsets(
    df: pd.DataFrame,
    column_config: ColumnConfig,
) -> tuple[pd.DataFrame, int, int, int]:
    """
    Add/overwrite the configured offset column and mark return offset pairs.

    Matching rule:
    1. Start from rows whose quantity is negative.
    2. Find an unused positive row with the same product name and the opposite
       quantity.
    3. If multiple rows qualify, choose the row with the nearest bill date.
       Approval number, price, amount, and original row order are tie-breakers.
    """
    validate_required_columns(df, column_config.return_required_columns)

    result_df = df.copy()
    result_df[column_config.sales_offset_id] = ""

    quantities = _numeric_series(result_df[column_config.sales_quantity])
    dates = _date_series(result_df[column_config.sales_bill_date])
    prices = _numeric_series(result_df[column_config.sales_price])
    amounts = _numeric_series(result_df[column_config.sales_amount])

    negative_indices = list(result_df.index[quantities < 0])
    used_positive_indices: set[int] = set()
    matched_pairs = 0

    total_negative_rows = len(negative_indices)
    for progress_index, negative_index in enumerate(negative_indices, start=1):
        positive_index = _find_best_positive_match(
            result_df,
            quantities,
            dates,
            prices,
            amounts,
            negative_index,
            used_positive_indices,
            column_config,
        )
        if positive_index is None:
            _show_progress("退货冲销比对进度", progress_index, total_negative_rows)
            continue

        matched_pairs += 1
        offset_id = f"{matched_pairs:03d}"
        result_df.at[negative_index, column_config.sales_offset_id] = offset_id
        result_df.at[positive_index, column_config.sales_offset_id] = offset_id
        used_positive_indices.add(positive_index)
        _show_progress("退货冲销比对进度", progress_index, total_negative_rows)

    unmatched_negative_rows = len(negative_indices) - matched_pairs
    return result_df, len(negative_indices), matched_pairs, unmatched_negative_rows


def run_return_offset_check(
    input_path: Path,
    output_path: Path,
    column_config_path: Path,
) -> OffsetCheckResult:
    """Run the return offset check and save the marked workbook."""
    print("正在读取退货冲销相关文件...", flush=True)
    column_config = load_column_config(column_config_path)
    df = load_sales_data(input_path, column_config)
    print(f"文件读取完成，共 {len(df)} 行，开始比对。", flush=True)
    result_df, negative_rows, matched_pairs, unmatched_negative_rows = mark_return_offsets(
        df,
        column_config,
    )
    print("比对完成，正在写入结果文件...", flush=True)
    result_df.to_excel(output_path, index=False)
    print("结果文件写入完成。", flush=True)

    return OffsetCheckResult(
        output_path=output_path,
        total_rows=len(result_df),
        negative_rows=negative_rows,
        matched_pairs=matched_pairs,
        unmatched_negative_rows=unmatched_negative_rows,
    )


def run_sales_medical_compare(
    sales_input_path: Path,
    medical_input_path: Path,
    output_path: Path,
    column_config_path: Path,
) -> SalesMedicalCompareResult:
    """Compare sales-side orders with medical-side visit IDs and save the result."""
    print("正在读取销售端、医保端及列名配置文件...", flush=True)
    column_config = load_column_config(column_config_path)
    sales_df = load_compare_sales_data(sales_input_path, column_config)
    medical_df = load_compare_medical_data(medical_input_path, column_config)

    print("文件读取完成，正在汇总销售单和医保就诊记录...", flush=True)
    sales_bills = _summarize_bills(
        sales_df,
        bill_id_column=column_config.sales_order_id,
        amount_column=column_config.sales_amount,
        time_column=column_config.sales_bill_date,
    )
    medical_bills = _summarize_bills(
        medical_df,
        bill_id_column=column_config.medical_visit_id,
        amount_column=column_config.medical_amount,
        time_column=column_config.medical_settlement_time,
    )
    print(
        f"汇总完成：销售单 {len(sales_bills)} 个，医保就诊记录 {len(medical_bills)} 个。",
        flush=True,
    )

    sales_amount_index = _sales_bill_amount_index(sales_bills)
    sales_date_index, sales_hour_index = _sales_bill_time_indexes(sales_bills)
    used_sales_bill_ids: set[str] = set()
    bill_matches: dict[str, tuple[BillSummary, str]] = {}
    incomplete_matched_bill_count = 0
    third_matched_bill_count = 0

    print("开始第一轮完全匹配...", flush=True)
    for progress_index, medical_bill in enumerate(medical_bills, start=1):
        sales_bill = _find_best_sales_bill_match(
            medical_bill,
            sales_amount_index,
            used_sales_bill_ids,
            column_config,
        )
        if sales_bill is not None:
            used_sales_bill_ids.add(sales_bill.bill_id)
            bill_matches[medical_bill.bill_id] = (sales_bill, MATCH_STATUS_EXACT)
        _show_progress("第一轮比对进度", progress_index, len(medical_bills))

    unmatched_medical_bills = [
        medical_bill
        for medical_bill in medical_bills
        if medical_bill.bill_id not in bill_matches
    ]
    print(
        f"第一轮完成，完全匹配 {len(bill_matches)} 个；"
        f"开始第二轮不完全匹配，共 {len(unmatched_medical_bills)} 个待处理。",
        flush=True,
    )

    for progress_index, medical_bill in enumerate(unmatched_medical_bills, start=1):
        sales_bill = _find_best_secondary_sales_bill_match(
            medical_bill,
            sales_date_index,
            sales_hour_index,
            used_sales_bill_ids,
            column_config,
        )
        if sales_bill is not None:
            used_sales_bill_ids.add(sales_bill.bill_id)
            bill_matches[medical_bill.bill_id] = (sales_bill, MATCH_STATUS_INCOMPLETE)
            incomplete_matched_bill_count += 1
        _show_progress(
            "第二轮比对进度",
            progress_index,
            len(unmatched_medical_bills),
        )

    third_round_medical_bills = [
        medical_bill
        for medical_bill in unmatched_medical_bills
        if medical_bill.bill_id not in bill_matches
    ]
    print(
        f"第二轮完成，不完全匹配 {incomplete_matched_bill_count} 个；"
        f"开始第三轮金额与商品匹配，共 {len(third_round_medical_bills)} 个待处理。",
        flush=True,
    )
    for progress_index, medical_bill in enumerate(third_round_medical_bills, start=1):
        sales_bill = _find_best_third_sales_bill_match(
            medical_bill,
            sales_amount_index,
            used_sales_bill_ids,
            column_config,
        )
        if sales_bill is not None:
            used_sales_bill_ids.add(sales_bill.bill_id)
            bill_matches[medical_bill.bill_id] = (sales_bill, MATCH_STATUS_INCOMPLETE)
            incomplete_matched_bill_count += 1
            third_matched_bill_count += 1
        _show_progress(
            "第三轮比对进度",
            progress_index,
            len(third_round_medical_bills),
        )

    print("匹配完成，正在整理输出明细...", flush=True)
    output_rows: list[dict[str, object]] = []
    for progress_index, medical_bill in enumerate(medical_bills, start=1):
        matched_sales_bill, match_status = bill_matches.get(
            medical_bill.bill_id,
            (None, MATCH_STATUS_UNMATCHED),
        )
        output_rows.extend(
            _build_compare_rows(
                medical_bill,
                matched_sales_bill,
                match_status,
                column_config,
            )
        )
        _show_progress("输出明细整理进度", progress_index, len(medical_bills))

    result_df = pd.DataFrame(output_rows, columns=COMPARE_OUTPUT_COLUMNS)
    print("明细整理完成，正在写入结果文件...", flush=True)
    result_df.to_excel(output_path, index=False)
    print("结果文件写入完成。", flush=True)

    matched_bill_count = len(bill_matches)

    return SalesMedicalCompareResult(
        output_path=output_path,
        medical_bill_count=len(medical_bills),
        matched_bill_count=matched_bill_count,
        incomplete_matched_bill_count=incomplete_matched_bill_count,
        third_matched_bill_count=third_matched_bill_count,
        unmatched_bill_count=len(medical_bills) - matched_bill_count,
        output_rows=len(result_df),
    )


def run_prescription_medical_compare(
    prescription_input_path: Path,
    medical_input_path: Path,
    catalog_input_path: Path,
    output_path: Path,
    column_config_path: Path,
) -> PrescriptionMedicalCompareResult:
    """Run prescription/medical matching, then mark prescription-drug catalog entries."""
    print("正在读取处方端、医保端、处方药目录及列名配置文件...", flush=True)
    column_config = load_column_config(column_config_path)
    prescription_df = load_prescription_data(prescription_input_path, column_config)
    medical_df = load_prescription_medical_data(medical_input_path, column_config)
    catalog_df = load_prescription_drug_catalog(catalog_input_path)

    print(f"文件读取完成，共 {len(medical_df)} 条医保明细，开始处方医保比对。", flush=True)
    result_df, normal_rows, after_medicine_rows, missing_rows = compare_prescriptions_to_medical(
        medical_df,
        prescription_df,
        column_config,
    )
    print("处方医保比对完成，开始处方药目录比对。", flush=True)
    result_df, prescription_drug_rows, non_prescription_drug_rows = (
        compare_medical_sales_to_prescription_drugs(
            result_df,
            catalog_df,
            medical_product_column=column_config.medical_product_name,
        )
    )
    print("全部比对完成，正在写入最终结果文件...", flush=True)
    result_df.to_csv(output_path, index=False, encoding="utf-8-sig")
    print("结果文件写入完成。", flush=True)

    return PrescriptionMedicalCompareResult(
        output_path=output_path,
        total_rows=len(result_df),
        normal_rows=normal_rows,
        after_medicine_rows=after_medicine_rows,
        missing_rows=missing_rows,
        prescription_drug_rows=prescription_drug_rows,
        non_prescription_drug_rows=non_prescription_drug_rows,
    )


def prompt_path(prompt_text: str, default_file: str) -> Path:
    value = input(f"{prompt_text}（直接回车使用 {default_file}）：").strip()
    return Path(value or default_file)


def print_menu() -> None:
    print()
    print("查宝（药店版）命令行工具")
    print("1. 生成列名配置表")
    print("2. 退货冲销检查")
    print("3. 销售端与医保端比对")
    print("4. 处方端医保端比对")
    print("0. 退出")


def main() -> None:
    while True:
        print_menu()
        choice = input("请输入菜单数字：").strip()

        if choice == "1":
            output_path = prompt_path("请输入列名配置表输出路径", DEFAULT_COLUMN_CONFIG_FILE)
            try:
                result_path = create_column_config_template(output_path)
            except Exception as exc:
                print(f"执行失败：{exc}")
                continue

            print("列名配置表已生成")
            print(f"输出文件：{result_path}")
        elif choice == "2":
            input_path = prompt_path("请输入销售明细 Excel 文件路径", DEFAULT_INPUT_FILE)
            output_path = prompt_path("请输入输出 Excel 文件路径", DEFAULT_OUTPUT_FILE)
            column_config_path = prompt_path(
                "请输入列名配置 Excel 文件路径",
                DEFAULT_COLUMN_CONFIG_FILE,
            )
            try:
                result = run_return_offset_check(input_path, output_path, column_config_path)
            except Exception as exc:
                print(f"执行失败：{exc}")
                continue

            print("退货冲销检查完成")
            print(f"总行数：{result.total_rows}")
            print(f"负数数量行：{result.negative_rows}")
            print(f"已标记冲销对数：{result.matched_pairs}")
            print(f"未匹配负数行：{result.unmatched_negative_rows}")
            print(f"输出文件：{result.output_path}")
        elif choice == "3":
            sales_input_path = prompt_path("请输入销售端 Excel 文件路径", DEFAULT_COMPARE_SALES_FILE)
            medical_input_path = prompt_path("请输入医保端 CSV 文件路径", DEFAULT_COMPARE_MEDICAL_FILE)
            output_path = prompt_path("请输入输出 Excel 文件路径", DEFAULT_COMPARE_OUTPUT_FILE)
            column_config_path = prompt_path(
                "请输入列名配置 Excel 文件路径",
                DEFAULT_COLUMN_CONFIG_FILE,
            )
            try:
                result = run_sales_medical_compare(
                    sales_input_path,
                    medical_input_path,
                    output_path,
                    column_config_path,
                )
            except Exception as exc:
                print(f"执行失败：{exc}")
                continue

            print("销售端与医保端比对完成")
            print(f"医保端编号数：{result.medical_bill_count}")
            print(f"已匹配编号数：{result.matched_bill_count}")
            print(f"不完全匹配编号数：{result.incomplete_matched_bill_count}")
            print(f"其中第三轮匹配编号数：{result.third_matched_bill_count}")
            print(f"未匹配编号数：{result.unmatched_bill_count}")
            print(f"输出行数：{result.output_rows}")
            print(f"输出文件：{result.output_path}")
        elif choice == "4":
            prescription_input_path = prompt_path(
                "请输入处方明细 Excel 文件路径",
                DEFAULT_PRESCRIPTION_FILE,
            )
            medical_input_path = prompt_path(
                "请输入医保端 CSV 文件路径",
                DEFAULT_PRESCRIPTION_MEDICAL_FILE,
            )
            catalog_input_path = prompt_path(
                "请输入处方药目录 Excel 文件路径",
                DEFAULT_PRESCRIPTION_DRUG_CATALOG_FILE,
            )
            output_path = prompt_path(
                "请输入输出 CSV 文件路径",
                DEFAULT_PRESCRIPTION_COMPARE_OUTPUT_FILE,
            )
            column_config_path = prompt_path(
                "请输入列名配置 Excel 文件路径",
                DEFAULT_COLUMN_CONFIG_FILE,
            )
            try:
                result = run_prescription_medical_compare(
                    prescription_input_path,
                    medical_input_path,
                    catalog_input_path,
                    output_path,
                    column_config_path,
                )
            except Exception as exc:
                print(f"执行失败：{exc}")
                continue

            print("处方端医保端综合比对完成")
            print(f"医保端总行数：{result.total_rows}")
            print(f"正常开方行数：{result.normal_rows}")
            print(f"先药后方行数：{result.after_medicine_rows}")
            print(f"无处方行数：{result.missing_rows}")
            print(f"处方药行数：{result.prescription_drug_rows}")
            print(f"非处方药行数：{result.non_prescription_drug_rows}")
            print(f"输出文件：{result.output_path}")
        elif choice == "0":
            print("已退出")
            break
        else:
            print("无效选项，请重新输入。")


if __name__ == "__main__":
    main()
